import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sitebar from "./components/utility/Sitebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <div className="flex h-dvh gap-2 p-1">
                    <div className="flex-1 p-4 rounded border bg-white shadow border-x">
                        <Sitebar />
                    </div>
                    <div className="flex-5 p-4 rounded border bg-white shadow border-x">{children}</div>
                </div>
            </body>
        </html>
    );
}
